name: Docker build image and list
description: Build image and list using Dockerfile
inputs:
  path_dockerfile:
    description: "This allows us to target the correct Dockerfile, even if it has a different name or is located in a different directory."
    required: false
    default: "Dockerfile"
  image_name:
    description: "Specifies the name for the generated Docker image"
    required: false
  tag_name:
    description: "Specifies the tag to be added to the final image"
    required: false
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          export TAG=$(date +%s)
        else
          export TAG="${{ inputs.tag_name }}"
        fi
        docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ inputs.image_name}}:$TAG
        
        docker image ls
      shell: bash






